config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :categories

  root 'posts#index'

  resources :users
  resources :sessions
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :connections
  has_many :posts, through: :connections
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :connections
  has_many :categories, through: :connections

  belongs_to :user


  validates :title, :content, presence: {message: "cannot be blank"}
  validates :title, :content, length: {minimum: 1, message: "is too short, minimum 1 character" }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_secure_password

  def author?(id)
    self == Post.find(id).user
  end

  validates :username, :password, presence: true
  validates :password, :username, length: {minimum: 2}
  validates :password, :username, length: {maximum: 20}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_author
    redirect_to login_path unless current_user.author?(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    @post.comments << @comment

    @comment.save
    redirect_to post_path(@post)
  end

  private 

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_author, only:[:edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(title: params[:title], content: params[:content])
    @post.user = current_user

    all_cat = Category.all.pluck(:title) #get all current category titles
    user_cat = params[:categories].split(",") #parse all user categories input

    #trim any white spaces
    user_cat.each do |cat|
      cat.strip!
    end

    #For existing categories associate it with the post
    (all_cat & user_cat).each do |cat|
      @post.categories << Category.find_by_title(cat)
    end

    #For new categories create the category and associate it with post
    (user_cat - all_cat).each do |cat|
      @post.categories << Category.create(title: cat)
    end
 
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      redirect_to post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    @post.comments.each do |comment|
      comment.destroy
    end
    
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_username(params[:session][:username])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id   #create a session for the user
      redirect_to posts_path
    else
      redirect_to 'login/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= render 'shared/title', title: "All Category" %>

<div>

  <% @categories.each do |category| %>
  <p><%= link_to category.title, category_path(category) %>
      (<%= category.posts.size %> posts)</p>
  <% end %>
  
</div>

app/views/categories/show.html.erb
<%= render 'shared/title', title: @category.title %>

<div>
  <% @category.posts.each do |post| %>
    <div>
      <h3><%= post.title %></h3>
      <p><%= post.content %></p>

      <%= link_to "show post", post_path(post) %>
      
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= render 'shared/title', title: "Edit Post" %>

<div>
  <%= form_for @post do |f| %>
    <p>Title</p>
    <p><%= f.text_field :title %></p>

    <p>Content</p>
    <p><%= f.text_area :content %></p>

    <p>Category</p>
      <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :title) do |cbox|%>
        <%= cbox.label(class: "checkbox-inline") { cbox.check_box(class: "checkbox") + cbox.text } %>
      <% end %>

    <p><%= f.submit %></p>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'shared/title', title: "All Posts" %>

<span class="btn btn-warning">
<%= link_to "new post", new_post_path %>
</span>

<span class="btn btn-warning">
<%= link_to "All Categories", categories_path %>
</span>

<% if current_user %>
  <span class="btn btn-warning">
  <%= link_to "Sign out", logout_path %>
  </span>

<% else %>
  <span class="btn btn-warning">
  <%= link_to "Sign up", new_user_path %>
  </span>

  <span class="btn btn-warning">
  <%= link_to "Log in", login_path %>
  </span>
<% end %>


<div>
  <% @posts.each do |post| %>
    <div class="well col-md-8">
      <h3><%= post.title %></h3>
      <p><%= simple_format(post.content) %></p>

      <% if !post.user.nil? %>
        <p> posted by <%= post.user.username %></p>
      <% end %>

      <%= link_to "show post", post_path(post) %>
      
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/title', title: "New Post" %>

<div>
  <%= form_tag @post do |f| %>
    <%= render 'shared/form_errors', object: @post %>
    
    <p>Title</p>
    <p><%= text_field_tag :title, params[:title] %></p>

    <p>Content</p>
    <p><%= text_area_tag :content, params[:content] %></p>

    <p>Category</p>
    <p><%= text_field_tag :categories, params[:categories] %></p>

    <p><%= submit_tag "New Post" %></p>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render 'shared/title', title: @post.title %>

<div>
  <h3><%= @post.title %></h3>
  <p><%= @post.content %></p>
  <% if !@post.user.nil? %>
   <p> posted by <%= @post.user.username %></p>
  <% end %>

  <% if current_user && current_user.author?(@post.id) %>
    <%= link_to "Edit Post", edit_post_path %>
    <%= link_to "Delete Post", post_path(@post), :method => :delete %>
  <% end %>

</div>

<p><%= link_to "back to all posts", posts_path %></p>

<!-- to display all comments -->
<div>
  <% @post.comments.each do |comment| %>
    <div>
      <%= comment.content %>
      <% if !comment.user.nil? %>
        by <%= comment.user.username %>
      <% end %>

    </div>
  <% end %>
</div>

<!-- the form for creating new comment -->
<div>
  <%= form_for [@post, @comment] do |f| %>
    <p><%= f.text_area :content %></p>

    <p><%= f.submit %></p>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p>
      <%= pluralize(object.errors.count, "error") %> prevented the form from being saved
    </p>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_title.html.erb
<h1><%= title %></h1>
<hr>

app/views/users/new.html.erb
<%= render 'shared/title', title: "Sign up" %>

<div>
  <%= form_for @user do |f| %>
    <%= render 'shared/form_errors', object: @user %>
    
    <p>username:</p>
    <p><%= f.text_field :username %></p>

    <p>password:</p>
    <p><%= f.password_field :password %></p>

    <%= f.submit "Sign up" %>
  <% end %>
</div>